blueprint:
  name: Duco Smart Ventilation (OpenAir Ready + Free@home Max)
  description: |
    3-speed Duco + OpenAir valves (optional) + toilet boost + Free@home manual max.
    Fully graphical – add valves anytime.
  domain: automation
  input:
    duco_fan:
      name: Duco Silent Box
      selector:
        entity:
          domain: fan

    valve_living:
      name: OpenAir Valve – Living Room
      default: ""
      selector:
        entity:
          domain: cover
          multiple: false
    valve_bathroom:
      name: OpenAir Valve – Bathroom
      default: ""
      selector:
        entity:
          domain: cover
          multiple: false
    valve_toilet:
      name: OpenAir Valve – Toilet
      default: ""
      selector:
        entity:
          domain: cover
          multiple: false
    valve_washing:
      name: OpenAir Valve – Washing Room
      default: ""
      selector:
        entity:
          domain: cover
          multiple: false

    hum_living:
      name: Humidity – Living (real-time)
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_living_5min:
      name: Humidity – Living 5min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_living_60min:
      name: Humidity – Living 60min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bathroom:
      name: Humidity – Bathroom (real-time)
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bathroom_5min:
      name: Humidity – Bathroom 5min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bathroom_60min:
      name: Humidity – Bathroom 60min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bedroom:
      name: Humidity – Bedroom (real-time)
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bedroom_5min:
      name: Humidity – Bedroom 5min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity
    hum_bedroom_60min:
      name: Humidity – Bedroom 60min avg
      selector:
        entity:
          domain: sensor
          device_class: humidity

    temp_inside:
      name: Inside Temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temp_outside:
      name: Outside Temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature
    co2_living:
      name: CO₂ Sensor (Living)
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide
    co2_bedroom:
      name: CO₂ Sensor (Bedroom) – optional
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide

    toilet_occupancy:
      name: Toilet Motion Sensor
      selector:
        entity:
          domain: binary_sensor

    manual_max_boost:
      name: Free@home Max Speed Toggle
      selector:
        entity:
          domain: [switch, input_boolean]

    hum_spike_up:
      name: Humidity spike to start
      default: 10
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: "%"
    hum_spike_down:
      name: Humidity drop to stop
      default: 1
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "%"
    hum_abs_down:
      name: Absolute humidity to stop
      default: 72
      selector:
        number:
          min: 50
          max: 85
          unit_of_measurement: "%"

    temp_activation:
      name: Inside temp to enable ΔT
      default: 22
      selector:
        number:
          min: 18
          max: 28
          unit_of_measurement: "°C"
    temp_delta_up:
      name: ΔT to start
      default: 3
      selector:
        number:
          min: 1
          max: 8
          unit_of_measurement: "°C"
    temp_delta_down:
      name: ΔT to stop
      default: 1
      selector:
        number:
          min: 0
          max: 5
          unit_of_measurement: "°C"

    co2_up:
      name: CO₂ start level
      default: 800
      selector:
        number:
          min: 500
          max: 1500
          unit_of_measurement: ppm
    co2_down:
      name: CO₂ stop level
      default: 600
      selector:
        number:
          min: 400
          max: 1200
          unit_of_measurement: ppm

    speed_high:
      name: High speed
      default: 100
      selector:
        number:
          min: 70
          max: 100
          unit_of_measurement: "%"
    speed_medium:
      name: Medium speed
      default: 50
      selector:
        number:
          min: 30
          max: 70
          unit_of_measurement: "%"
    speed_low:
      name: Low speed
      default: 15
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input hum_living
  - platform: state
    entity_id: !input hum_living_5min
  - platform: state
    entity_id: !input hum_living_60min
  - platform: state
    entity_id: !input hum_bathroom
  - platform: state
    entity_id: !input hum_bathroom_5min
  - platform: state
    entity_id: !input hum_bathroom_60min
  - platform: state
    entity_id: !input hum_bedroom
  - platform: state
    entity_id: !input hum_bedroom_5min
  - platform: state
    entity_id: !input hum_bedroom_60min
  - platform: state
    entity_id: !input temp_inside
  - platform: state
    entity_id: !input temp_outside
  - platform: state
    entity_id: !input co2_living
  - platform: state
    entity_id: !input co2_bedroom
  - platform: state
    entity_id: !input toilet_occupancy
  - platform: state
    entity_id: !input manual_max_boost
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: template
    value_template: "{{ is_state('input_select.ventilation_manual_mode', 'Auto') }}"

action:
  - variables:
      h_liv:     "{{ states(!input hum_living) | float }}"
      h_liv_5m:  "{{ states(!input hum_living_5min) | float }}"
      h_liv_60m: "{{ states(!input hum_living_60min) | float }}"
      h_bath:    "{{ states(!input hum_bathroom) | float }}"
      h_bath_5m: "{{ states(!input hum_bathroom_5min) | float }}"
      h_bath_60m: "{{ states(!input hum_bathroom_60min) | float }}"
      h_bed:     "{{ states(!input hum_bedroom) | float }}"
      h_bed_5m:  "{{ states(!input hum_bedroom_5min) | float }}"
      h_bed_60m: "{{ states(!input hum_bedroom_60min) | float }}"
      t_in:      "{{ states(!input temp_inside) | float }}"
      t_out:     "{{ states(!input temp_outside) | float }}"
      co2_l:     "{{ states(!input co2_living) | float }}"
      co2_b:     "{{ states(!input co2_bedroom) | float if !input co2_bedroom else 0 }}"

      spike_living:   "{{ (h_liv - h_liv_5m) > !input hum_spike_up }}"
      spike_bathroom: "{{ (h_bath - h_bath_5m) > !input hum_spike_up }}"
      spike_bedroom:  "{{ (h_bed - h_bed_5m) > !input hum_spike_up }}"
      ok_living:   "{{ (h_liv - h_liv_60m) < !input hum_spike_down and h_liv < !input hum_abs_down }}"
      ok_bathroom: "{{ (h_bath - h_bath_60m) < !input hum_spike_down and h_bath < !input hum_abs_down }}"
      ok_bedroom:  "{{ (h_bed - h_bed_60m) < !input hum_spike_down and h_bed < !input hum_abs_down }}"

      hum_spike: "{{ spike_living or spike_bathroom or spike_bedroom }}"
      hum_ok:    "{{ ok_living and ok_bathroom and ok_bedroom }}"
      temp_active: "{{ t_in > !input temp_activation and (t_in - t_out) > !input temp_delta_up }}"
      temp_ok:     "{{ t_in <= !input temp_activation or (t_in - t_out) < !input temp_delta_down }}"
      co2_high:    "{{ co2_l > !input co2_up or co2_b > !input co2_up }}"
      co2_ok:      "{{ co2_l < !input co2_down and (!input co2_bedroom == '' or co2_b < !input co2_down) }}"

      need_high:   "{{ hum_spike or temp_active or co2_high }}"
      need_medium: "{{ not need_high and ((h_liv - h_liv_5m) > (!input hum_spike_up * 0.6) or (h_bath - h_bath_5m) > (!input hum_spike_up * 0.6) or (h_bed - h_bed_5m) > (!input hum_spike_up * 0.6) or (t_in - t_out) > (!input temp_delta_up * 0.6) or co2_l > (!input co2_up * 0.8)) }}"
      all_ok:      "{{ hum_ok and temp_ok and co2_ok }}"

      valves_exist: "{{ !input valve_living != '' or !input valve_bathroom != '' or !input valve_toilet != '' or !input valve_washing != '' }}"

      toilet_active: "{{ is_state(!input toilet_occupancy, 'on') }}"
      timer_state: "{{ states('timer.toilet_ventilation') }}"
      timer_remaining: "{{ state_attr('timer.toilet_ventilation', 'remaining') | default('0:00:00') }}"
      toilet_boost_active: "{{ timer_state in ['active', 'paused'] and timer_remaining != '0:00:00' }}"

  # ── FREE@HOME MANUAL MAX OVERRIDE ─────────────────────
  - choose:
      - conditions:
          - "{{ is_state(!input manual_max_boost, 'on') }}"
        sequence:
          - service: fan.turn_on
            target:
              entity_id: !input duco_fan
          - service: fan.set_percentage
            data:
              percentage: 100
            target:
              entity_id: !input duco_fan
          - if:
              - condition: template
                value_template: "{{ valves_exist }}"
            then:
              - service: cover.close_cover
                target:
                  entity_id:
                    - !input valve_living
                    - !input valve_bathroom
                    - !input valve_toilet
                    - !input valve_washing
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.ventilation_enabled_triggered
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.ventilation_disabled_triggered

  # ── TOILET BOOST ─────────────────────────────────────
  - choose:
      - conditions: "{{ toilet_active and timer_state != 'active' }}"
        sequence:
          - service: timer.start
            target:
              entity_id: timer.toilet_ventilation
  - choose:
      - conditions: "{{ not toilet_active and timer_state == 'active' and timer_remaining > '0:05:00' }}"
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.toilet_ventilation
  - choose:
      - conditions:
          - "{{ toilet_boost_active and is_state('input_boolean.ventilation_enabled_triggered', 'off') and is_state(!input manual_max_boost, 'off') }}"
        sequence:
          - service: fan.turn_on
            target:
              entity_id: !input duco_fan
          - service: fan.set_percentage
            data:
              percentage: 100
            target:
              entity_id: !input duco_fan
          - if:
              - condition: template
                value_template: "{{ valves_exist }}"
            then:
              - service: cover.close_cover
                target:
                  entity_id:
                    - !input valve_living
                    - !input valve_bathroom
                    - !input valve_toilet
                    - !input valve_washing
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.ventilation_enabled_triggered
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.ventilation_disabled_triggered

  # ── NORMAL LOGIC ─────────────────────────────────────
  - choose:
      - conditions:
          - "{{ not toilet_boost_active and is_state(!input manual_max_boost, 'off') }}"
          - "{{ is_state('input_select.ventilation_manual_mode', 'Auto') }}"
        sequence:
          - choose:
              # HIGH
              - conditions:
                  - "{{ need_high }}"
                  - "{{ is_state('input_boolean.ventilation_enabled_triggered', 'off') }}"
                sequence:
                  - service: fan.turn_on
                    target:
                      entity_id: !input duco_fan
                  - service: fan.set_percentage
                    data:
                      percentage: !input speed_high
                    target:
                      entity_id: !input duco_fan
                  - if:
                      - condition: template
                        value_template: "{{ valves_exist }}"
                    then:
                      - service: cover.open_cover
                        target:
                          entity_id:
                            - !input valve_living
                            - !input valve_bathroom
                            - !input valve_toilet
                            - !input valve_washing
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.ventilation_enabled_triggered
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ventilation_disabled_triggered

              # MEDIUM
              - conditions:
                  - "{{ need_medium }}"
                  - "{{ is_state('input_boolean.ventilation_enabled_triggered', 'off') }}"
                sequence:
                  - service: fan.set_percentage
                    data:
                      percentage: !input speed_medium
                    target:
                      entity_id: !input duco_fan
                  - if:
                      - condition: template
                        value_template: "{{ !input valve_bathroom != '' and (spike_bathroom or (h_bath - h_bath_5m) > (!input hum_spike_up * 0.6)) }}"
                    then:
                      - service: cover.open_cover
                        target:
                          entity_id: !input valve_bathroom
                      - if:
                          - condition: template
                            value_template: "{{ !input valve_living != '' }}"
                        then:
                          - service: cover.close_cover
                            target:
                              entity_id: !input valve_living
                  - if:
                      - condition: template
                        value_template: "{{ !input valve_living != '' and (co2_high or temp_active or spike_living or spike_bedroom) }}"
                    then:
                      - service: cover.open_cover
                        target:
                          entity_id: !input valve_living
                      - if:
                          - condition: template
                            value_template: "{{ !input valve_bathroom != '' }}"
                        then:
                          - service: cover.close_cover
                            target:
                              entity_id: !input valve_bathroom
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.ventilation_enabled_triggered
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ventilation_disabled_triggered

              # LOW
              - conditions:
                  - "{{ all_ok }}"
                  - "{{ is_state('input_boolean.ventilation_disabled_triggered', 'off') }}"
                sequence:
                  - service: fan.set_percentage
                    data:
                      percentage: !input speed_low
                    target:
                      entity_id: !input duco_fan
                  - if:
                      - condition: template
                        value_template: "{{ valves_exist }}"
                    then:
                      - service: cover.close_cover
                        target:
                          entity_id:
                            - !input valve_living
                            - !input valve_bathroom
                            - !input valve_toilet
                            - !input valve_washing
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.ventilation_disabled_triggered
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ventilation_enabled_triggered

mode: single
max_exceeded: silent
